name: visual-token-diffuser-cpu
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pytorch=2.6.0
  - torchvision
  - numpy
  - matplotlib
  - tqdm
  - scikit-learn
  - pandas
  - jupyter
  - ipykernel
  - pytest
  - pip
  - pip:
      - tensorboard